server:
  port: 8888

spring:
  application:
    name: customer-service
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@0.tcp.ip.ngrok.io:17656:xe
    username: yj
    password: yj
  jpa:
    show-sql: true
    hibernate:
#            ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
